### ISSUE TITLE
How to compile your project without *.sln file?

### ISSUE THREAD

**Issue by Ponyoonthecliff** [unplugred/borderless#2]
Sorry for a noob's question, not a coder, just want to add some hotkeys (it's possible for non-coder), but can't compile your project.

1. Can't compile in VS without base *.sln file (looks like it's not included in sources). Tried to make empty project, that didn't work.
2. Can't compile in Developer Command Prompt for VS or MiniGW with the same error in both cases 'couldn't find QMainWindow'.

What am I doing wrong?

**Comment by unplugred** [comment]
Hey, this project used to be a Visual Studio C# project, but i ported it to QT in order to support linux.
If you want to open it, download QT Creator, though it is notoriously hard to install.
Alternatively, you can open the project from the time it used to be a C# project, which is commit number baae9e1fa479d28b6007f1515a4c52749f72efb2

Additionally, please keep the tickets to feature requests and bugs only, as I do not have the time needed to provide users with written tutorials.

Out of curiousity, which shortcuts do you want to add?

**Comment by bumfuzzleme** [comment]
Always on top + 'fixed zoom' function + something with double click 

Thanks for the info and sorry for any incovinience. I really appreciate your time, that's why I wanted (and still going to) to implement these fixes by myself.

Additionally, please add such an info into your project from the beginning, as I and any other people do not have time to search for something like that.

**Comment by unplugred** [comment]
fair enough, point taken. didnt really think anybody would actually see this project.
the last time i worked on it was a really really long time ago so i probably wont be able to provide details such as the qt version or what not... but ill add the info that i can
